image: python:3.9-slim

stages:
    - tests
    - deploy

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: &global_cache
    key:
        files:
            - poetry.lock
            - .gitlab-ci.yml
        prefix: ${CI_JOB_NAME}
    paths:
        - .venv
        - .cache/pip
    policy: pull

before_script:
    - python -V
    - pip install poetry

test:
    stage: tests
    cache:
        <<: *global_cache
        policy: pull-push
    script:
        - poetry install
        - poetry build
        - poetry run pytest --cov --html=htmlcov/results.html --self-contained-html --junitxml=report.xml --cov-report=xml --cov-report=html
    artifacts:
        reports:
            junit: report.xml
            cobertura: coverage.xml
        paths:
            - htmlcov/

pages:
    stage: deploy
    needs: ["test"]
    script:
        - mv htmlcov/ public/
    artifacts:
        paths:
            - public/
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master"'

deploy:
    stage: deploy
    needs: ["test"]
    script:
        - poetry publish -r gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN} --build
    rules:
        - if: $CI_COMMIT_TAG
