image: python:3.9-slim

stages:
    - tests
    - deploy

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    key:
        files:
            - poetry.lock
            - .gitlab-ci.yml
        prefix: ${CI_JOB_NAME}
    paths:
        - .venv
        - .cache/pip

before_script:
    - python -V
    - pip install poetry

test:
    stage: tests
    script:
        - poetry install
        - poetry build
        - poetry run pytest --cov=setup_creator/ --cov-branch --junitxml=report.xml
        - poetry run coverage xml
    artifacts:
        reports:
            junit: report.xml
            cobertura: coverage.xml

deploy:
    only:
        - tags
    stage: deploy
    script:
        - poetry publish -r gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN} --build
